### ISSUE TITLE
Possible to increase the sonata admin bundle version to ^3.4 ?

### ISSUE THREAD

**Issue by spacetraveller** [whyte624/sonata-admin-extra-export-bundle#4]
I have the latest Sonata Admin bundle installed, and need to add this exporter to my project. Is it possible to increase the requirement to ^3.4 ?

**Comment by whyte624** [comment]
Why not! Make a pull request.

**Comment by alsii** [comment]
I have made the pull request. Check and merge it please as soon as possible!

**Comment by whyte624** [comment]
https://github.com/whyte624/sonata-admin-extra-export-bundle/pull/5
