### ISSUE TITLE
New release (1.2) is needed, due to requirements change

### ISSUE THREAD

**Issue by alsii** [whyte624/sonata-admin-extra-export-bundle#6]

**Comment by alsii** [comment]
@whyte624 Could you please make a new release (1.2) to provide new requirements information for packagist.org? Thank you!

**Comment by whyte624** [comment]
https://github.com/whyte624/sonata-admin-extra-export-bundle/releases/tag/1.2

**Comment by alsii** [comment]
Danke sehr!

2017-09-19 12:23 GMT+02:00 Andrei Sozonov <notifications@github.com>:
